<?php

/**
 * SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace OCA\Tables\Service;

use OCA\Tables\Errors\BadRequestError;
use OCA\Tables\Errors\InternalError;
use OCA\Tables\Errors\NotFoundError;
use OCA\Tables\Errors\PermissionError;
use OCP\App\IAppManager;
use Psr\Log\LoggerInterface;

class StructureDiffService extends SuperService {
	private const MAX_COLUMNS = 500;
	private const MAX_VIEWS = 100;

	private const COLUMN_DIFFABLE_FIELDS = [
		'description', 'mandatory', 'textDefault', 'textAllowedPattern',
		'textMaxLength', 'textUnique', 'numberDefault', 'numberMin', 'numberMax',
		'numberDecimals', 'numberPrefix', 'numberSuffix', 'selectionOptions',
		'selectionDefault', 'datetimeDefault', 'usergroupDefault',
		'usergroupMultipleItems', 'usergroupSelectUsers', 'usergroupSelectGroups',
		'usergroupSelectTeams', 'showUserStatus', 'customSettings', 'subtype',
	];

	private const VIEW_DIFFABLE_FIELDS = [
		'emoji', 'description', 'filter', 'sort', 'columns', 'columnSettings',
	];

	public function __construct(
		LoggerInterface $logger,
		?string $userId,
		PermissionsService $permissionsService,
		private TableService $tableService,
		private ColumnService $columnService,
		private ViewService $viewService,
		private IAppManager $appManager,
	) {
		parent::__construct($logger, $userId, $permissionsService);
	}

	/**
	 * Compute a structural diff between the current table state and an incoming scheme.
	 *
	 * @param int $tableId Target table ID
	 * @param array $scheme Incoming scheme (parsed JSON)
	 * @return array Diff payload
	 * @throws BadRequestError
	 * @throws InternalError
	 * @throws NotFoundError
	 * @throws PermissionError
	 */
	public function computeDiff(int $tableId, array $scheme): array {
		$this->validateSchemeStructure($scheme);
		$this->enforceArraySizeLimits($scheme);

		$table = $this->tableService->find($tableId, $this->userId);
		$targetColumns = $this->columnService->findAllByTable($tableId, $this->userId);
		$targetViews = $this->viewService->findAll($table, $this->userId);

		$diff = [];

		$versionWarning = $this->buildVersionWarning($scheme['tablesVersion'] ?? '');
		if ($versionWarning !== null) {
			$diff['versionWarning'] = $versionWarning;
		}

		$tableMeta = $this->diffTableMeta($table, $scheme);
		if (!empty($tableMeta)) {
			$diff['tableMeta'] = $tableMeta;
		}

		[$columnDiff, $columnMap] = $this->diffColumns($targetColumns, $scheme['columns']);
		if (!empty($columnDiff)) {
			$diff['columns'] = $columnDiff;
		}

		$viewDiff = $this->diffViews($targetViews, $scheme['views'] ?? [], $columnMap, $scheme['columns']);
		if (!empty($viewDiff)) {
			$diff['views'] = $viewDiff;
		}

		$diff['columnMap'] = $columnMap;

		return $diff;
	}

	/**
	 * @throws BadRequestError
	 */
	private function validateSchemeStructure(array $scheme): void {
		if (!isset($scheme['columns'], $scheme['views'])) {
			throw new BadRequestError('Invalid scheme structure: missing required keys "columns" or "views".');
		}
		if (!is_array($scheme['columns'])) {
			throw new BadRequestError('Invalid scheme structure: "columns" must be an array.');
		}
		if (!is_array($scheme['views'])) {
			throw new BadRequestError('Invalid scheme structure: "views" must be an array.');
		}
		foreach ($scheme['columns'] as $col) {
			if (!is_array($col)
				|| !isset($col['id'], $col['title'], $col['type'])
				|| !is_int($col['id'])
				|| !is_string($col['title'])
				|| !is_string($col['type'])
			) {
				throw new BadRequestError('Invalid scheme structure: each column must be an array with integer "id", string "title" and string "type".');
			}
		}
	}

	/**
	 * @throws BadRequestError
	 */
	private function enforceArraySizeLimits(array $scheme): void {
		if (count($scheme['columns']) > self::MAX_COLUMNS) {
			throw new BadRequestError('Payload exceeds maximum allowed size: "columns" must not exceed ' . self::MAX_COLUMNS . ' entries.');
		}
		if (count($scheme['views'] ?? []) > self::MAX_VIEWS) {
			throw new BadRequestError('Payload exceeds maximum allowed size: "views" must not exceed ' . self::MAX_VIEWS . ' entries.');
		}
	}

	private function buildVersionWarning(?string $schemeVersion): ?string {
		if ($schemeVersion === null || $schemeVersion === '') {
			return null;
		}
		$appVersion = $this->appManager->getAppVersion('tables');
		$schemeMajor = (int)explode('.', $schemeVersion)[0];
		$appMajor = (int)explode('.', $appVersion)[0];
		if ($schemeMajor !== $appMajor) {
			return sprintf(
				'Scheme was generated by Tables %s; this instance runs %s. Verify the result carefully.',
				$schemeVersion,
				$appVersion,
			);
		}
		return null;
	}

	private function diffTableMeta(\OCA\Tables\Db\Table $table, array $scheme): array {
		$changes = [];
		$fields = ['title', 'emoji', 'description'];
		$getters = ['title' => 'getTitle', 'emoji' => 'getEmoji', 'description' => 'getDescription'];
		foreach ($fields as $field) {
			if (!array_key_exists($field, $scheme)) {
				continue;
			}
			$current = $table->{$getters[$field]}();
			$incoming = $scheme[$field];
			if ($current !== $incoming) {
				$changes[$field] = ['current' => $current, 'incoming' => $incoming];
			}
		}
		return $changes;
	}

	/**
	 * @param \OCA\Tables\Db\Column[] $targetColumns
	 * @param array $sourceColumns
	 * @return array{0: array, 1: array}
	 */
	private function diffColumns(array $targetColumns, array $sourceColumns): array {
		$columnDiff = [];
		$columnMap = [];

		$targetByKey = [];
		foreach ($targetColumns as $col) {
			$key = strtolower($col->getTitle()) . '|' . $col->getType();
			$targetByKey[$key] = $col;
		}

		$matchedTargetIds = [];

		foreach ($sourceColumns as $srcCol) {
			$key = strtolower($srcCol['title']) . '|' . $srcCol['type'];
			if (isset($targetByKey[$key])) {
				$targetCol = $targetByKey[$key];
				$matchedTargetIds[] = $targetCol->getId();
				$columnMap[] = [
					'sourceName' => $srcCol['title'],
					'sourceType' => $srcCol['type'],
					'sourceId' => $srcCol['id'],
					'targetId' => $targetCol->getId(),
				];
				$changes = $this->diffColumnProperties($targetCol, $srcCol);
				if (!empty($changes)) {
					$changesObj = [];
					foreach ($changes as $change) {
						$changesObj[$change['field']] = ['current' => $change['current'], 'incoming' => $change['incoming']];
					}
					$columnDiff[] = [
						'action' => 'update',
						'targetId' => $targetCol->getId(),
						'column' => ['title' => $srcCol['title'], 'type' => $srcCol['type']],
						'changes' => $changesObj,
					];
				}
			} else {
				$columnMap[] = [
					'sourceName' => $srcCol['title'],
					'sourceType' => $srcCol['type'],
					'sourceId' => $srcCol['id'],
					'targetId' => null,
				];
				$columnDiff[] = [
					'action' => 'add',
					'column' => $srcCol,
				];
			}
		}

		foreach ($targetColumns as $targetCol) {
			if (!in_array($targetCol->getId(), $matchedTargetIds, true)) {
				$columnDiff[] = [
					'action' => 'delete',
					'targetId' => $targetCol->getId(),
					'column' => ['title' => $targetCol->getTitle(), 'type' => $targetCol->getType()],
				];
			}
		}

		return [$columnDiff, $columnMap];
	}

	private function diffColumnProperties(\OCA\Tables\Db\Column $targetCol, array $srcCol): array {
		$changes = [];
		$targetArr = $targetCol->jsonSerialize();
		foreach (self::COLUMN_DIFFABLE_FIELDS as $field) {
			$current = $targetArr[$field] ?? null;
			$incoming = $srcCol[$field] ?? null;
			$currentNorm = $this->normalizeForComparison($current);
			$incomingNorm = $this->normalizeForComparison($incoming);
			if ($currentNorm !== $incomingNorm) {
				$changes[] = ['field' => $field, 'current' => $current, 'incoming' => $incoming];
			}
		}
		return $changes;
	}

	/**
	 * Normalize a value for structural comparison.
	 * - false and null are treated as equivalent: boolean fields default to false in the DB
	 *   but are absent (null) when omitted from an exported scheme, so they must not
	 *   trigger a spurious "false → (none)" diff entry.
	 * - Arrays and objects (including \stdClass) are JSON-encoded so that e.g. an empty
	 *   \stdClass and an empty array compare as equal.
	 */
	private function normalizeForComparison(mixed $value): mixed {
		if ($value === false) {
			return null;
		}
		if (!is_array($value) && !is_object($value)) {
			return $value;
		}
		return json_encode(json_decode(json_encode($value), true));
	}

	/**
	 * @param \OCA\Tables\Db\View[] $targetViews
	 * @param array $sourceViews
	 * @param array $columnMap
	 * @param array $sourceColumns
	 * @return array
	 */
	private function diffViews(array $targetViews, array $sourceViews, array $columnMap, array $sourceColumns): array {
		$viewDiff = [];

		$targetByTitle = [];
		foreach ($targetViews as $view) {
			$targetByTitle[$view->getTitle()] = $view;
		}

		$sourceColumnIds = array_column($sourceColumns, 'id');
		$overriddenSelectionColumnIds = $this->findOverriddenSelectionColumnIds($columnMap);

		foreach ($sourceViews as $srcView) {
			$title = $srcView['title'] ?? '';
			if (!isset($targetByTitle[$title])) {
				$viewDiff[] = [
					'action' => 'add',
					'view' => $srcView,
				];
			} else {
				$targetView = $targetByTitle[$title];
				// Remap source column IDs to target IDs for comparison only;
				// the original $srcView values are used in the diff output for display.
				$srcViewRemapped = $this->remapIncomingViewForComparison($srcView, $columnMap);
				$changes = $this->diffViewProperties($targetView, $srcViewRemapped, $srcView);
				if (!empty($changes)) {
					$changesObj = [];
					foreach ($changes as $change) {
						$changesObj[$change['field']] = ['current' => $change['current'], 'incoming' => $change['incoming']];
					}
					$item = [
						'action' => 'update',
						'title' => $title,
						'changes' => $changesObj,
					];
					if ($this->hasSelectionFilterWarning($srcView, $overriddenSelectionColumnIds, $sourceColumnIds)) {
						$item['selectionFilterWarning'] = true;
					}
					$viewDiff[] = $item;
				}
			}
		}

		return $viewDiff;
	}

	private function diffViewProperties(
		\OCA\Tables\Db\View $targetView,
		array $srcViewForComparison,
		array $srcViewOriginal,
	): array {
		$changes = [];
		$targetArr = $targetView->jsonSerialize();
		foreach (self::VIEW_DIFFABLE_FIELDS as $field) {
			$current = $targetArr[$field] ?? null;
			$incoming = $srcViewForComparison[$field] ?? null;
			if (is_array($current)) {
				$current = json_encode($current);
			}
			if (is_array($incoming)) {
				$incoming = json_encode($incoming);
			}
			if ($current !== $incoming) {
				// Use original (non-remapped) incoming value in the diff output so
				// the frontend can resolve source column names for display.
				$changes[] = ['field' => $field, 'current' => $targetArr[$field] ?? null, 'incoming' => $srcViewOriginal[$field] ?? null];
			}
		}
		return $changes;
	}

	/**
	 * Remap source column IDs to target IDs in a view's structural fields for comparison.
	 * Source IDs without a matching target are left unchanged so they still produce a diff.
	 */
	private function remapIncomingViewForComparison(array $srcView, array $columnMap): array {
		$idMap = [];
		foreach ($columnMap as $entry) {
			if ($entry['targetId'] !== null) {
				$idMap[(int)$entry['sourceId']] = $entry['targetId'];
			}
		}

		$remapped = $srcView;

		if (isset($remapped['filter']) && is_array($remapped['filter'])) {
			foreach ($remapped['filter'] as &$group) {
				foreach ($group as &$cond) {
					if (isset($cond['columnId'])) {
						$cond['columnId'] = $idMap[(int)$cond['columnId']] ?? $cond['columnId'];
					}
				}
			}
		}

		if (isset($remapped['sort']) && is_array($remapped['sort'])) {
			foreach ($remapped['sort'] as &$rule) {
				if (isset($rule['columnId'])) {
					$rule['columnId'] = $idMap[(int)$rule['columnId']] ?? $rule['columnId'];
				}
			}
		}

		if (isset($remapped['columns']) && is_array($remapped['columns'])) {
			foreach ($remapped['columns'] as &$id) {
				$id = $idMap[(int)$id] ?? $id;
			}
		}

		if (isset($remapped['columnSettings']) && is_array($remapped['columnSettings'])) {
			foreach ($remapped['columnSettings'] as &$cs) {
				if (isset($cs['columnId'])) {
					$cs['columnId'] = $idMap[(int)$cs['columnId']] ?? $cs['columnId'];
				}
			}
		}

		return $remapped;
	}

	/**
	 * Returns the set of source column IDs whose selection options are being fully replaced.
	 * A column is considered "overridden" if it has an update action with a selectionOptions change.
	 */
	private function findOverriddenSelectionColumnIds(array $columnMap): array {
		$overridden = [];
		foreach ($columnMap as $entry) {
			if ($entry['targetId'] !== null && $entry['sourceType'] === 'selection') {
				$overridden[] = $entry['sourceId'];
			}
		}
		return $overridden;
	}

	/**
	 * Returns true when a view's filter JSON contains @selection-id-{id} tokens for columns
	 * whose selection options are being replaced.
	 */
	private function hasSelectionFilterWarning(array $srcView, array $overriddenSelectionColumnIds, array $allSourceColumnIds): bool {
		if (empty($overriddenSelectionColumnIds)) {
			return false;
		}
		$filterJson = is_array($srcView['filter'] ?? null)
			? json_encode($srcView['filter'])
			: ($srcView['filter'] ?? '');
		if (!is_string($filterJson) || $filterJson === '') {
			return false;
		}
		if (preg_match_all('/@selection-id-(\d+)/', $filterJson, $matches)) {
			foreach ($overriddenSelectionColumnIds as $id) {
				if (in_array((string)$id, $matches[1], true)) {
					return true;
				}
			}
		}
		return false;
	}
}
