export const ColumnTypes = {
	Datetime: 'datetime',
	DatetimeDate: 'datetime-date',
	DatetimeTime: 'datetime-time',
	Number: 'number',
	NumberProgress: 'number-progress',
	NumberStars: 'number-stars',
	Selection: 'selection',
	SelectionCheck: 'selection-check',
	SelectionMulti: 'selection-multi',
	TextIPv4Address: 'text-ipv4address',
	TextIPv6Address: 'text-ipv6address',
	TextLine: 'text-line',
	TextLink: 'text-link',
	TextLong: 'text-long',
	TextRich: 'text-rich',
}
